apiVersion: v1
kind: Service
metadata:
  name: cinder
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ExternalName
  externalName: loki.monitoring.svc.cluster.local
